@startuml

Alice -> Bob : message 1
Alice -> Bob : message 2

newpage

Alice -> Bob : message 3
Alice -> Bob : message 4

new page A title for the\last page

Alice -> Bob : message 5
Alice -> Bob : message 6
@enduml